
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    volumes:
          - sqlserver_data:/var/opt/mssqlMyDatabase
  smartcafeteriaorders:
    image: izabelarad/smartcafeteriaorders
    container_name: smartcafeteriaorders
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=MyDatabase;User Id=sa;Password=Password123;TrustServerCertificate=True;"
#    image: smartcafeteriaorders
#    build:
#      context: .
#      dockerfile: SmartCafeteriaOrders/Dockerfile
#    container_name: smartcafeteriaorders
#    ports:
#      - "8080:8080"
#    depends_on:
#      - sqlserver
#    environment:
#        ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=MyDatabase;User Id=sa;Password=Password123;TrustServerCertificate=True;"

volumes:
  sqlserver_data: